### ISSUE TITLE
Number of samples per epoch?

### ISSUE THREAD

**Issue by busycalibrating** [wzekai99/DM-Improves-AT#1]
I just wanted to confirm my understanding because I didn't see this in the paper: for each generated dataset (e.g. 1m, 10m, 50m, etc), you don't actually iterate over the full augmented datasets in each epoch, right? You're simply sampling from the true and generated datasets such that each epoch corresponds to the same number of training steps for the original dataset (e.g. for CIFAR10, you'd only see 50k training examples), albeit different samples each epoch due to the random sampling from the real and generated datasets.

i.e. here:

https://github.com/wzekai99/DM-Improves-AT/blob/main/core/data/semisup.py#L15

**Comment by P2333** [comment]
Yes, you are right! Actually this practice inherits from the [PyTorch implementation](https://github.com/imrahulr/adversarial_robustness_pytorch) of [Rebuffi et al., 2021](https://arxiv.org/abs/2103.01946), where the training time (i.e., number of iterations) is independent of the number of generated data. This is used for a fair comparison with W/O-generated-data baseline, and the only extra computation is to generate the 1m or 50m data.

Although we did not try, but we believe that fully running over the entire generated data (using certain original-to-generated ratios) could further improve the model performance beyond our results.

**Comment by busycalibrating** [comment]
Ok awesome!  To me that makes your results even cooler :smiley:
